### ISSUE TITLE
push-impersonationcontext

### ISSUE THREAD

**Issue by pwshfan** [claudiospizzi/SecurityFever#1]
Please see the following error, it happens on several environments: 

![image](https://user-images.githubusercontent.com/24714308/44105903-00cf912e-9feb-11e8-910d-5db405df16b4.png)

**Comment by claudiospizzi** [comment]
Hi @lelloz0 

Can you check version 2.2.1 of the module, should be fixed there.

Regards,
Claudio9

**Comment by pwshfan** [comment]
Thank you Claudio, I don't get the error anymore. However, after using ### **Push-ImpersonationContext** and issuing a **whoami** I still get the username of the account used to log on the server and used for that powershell session. Is there a way to confirm that, after using that cmdlet, all the commands will use the account pushed by the impersonation? Thank you

**Comment by claudiospizzi** [comment]
This is how impersonation works, I guess. The process is still running as the same user account in Windows, but the interaction is performed as the impersonated used. This is **not** a runas function. To get the current impersonation context and the current user, use the following command:
```
Get-ImpersonationContext
```

**Comment by pwshfan** [comment]
Yeah, the problem is that any consequential cmdlet that I run after pushing the impersonation with another user, does not seem to be executed with the impersonated user. I will look into it, thank you.

**Comment by claudiospizzi** [comment]
Maybe, the behavior is different for command that will be executed locally or against a remote system. I use this cmdlets to execute Active Directory cmdlets with another user against the Domain Controllers.

**Comment by pwshfan** [comment]
yeah, that works but I was trying to adopt it to primarily try to access a remote server with another set of credentials in the same PS Session (this is because I'm using Jenkins). I found that New-PSSessionConfiguration works for the scope.

**Comment by claudiospizzi** [comment]
Locks like `New-PSSessionConfiguration` is not a well known cmdlet. Do you maybe mean `Register-PSSessionConfiguration` or `New-PSSessionOption`?

Would be great if you can post the few lines how you achieve you goal, so that other with the same or similar issue have a solution. Thank you.

**Comment by pwshfan** [comment]
sorry: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-pssessionconfiguration
